# Generated by Django 5.2.16 on 2026-07-30 16:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=12, unique=True)),
                ('first_name', models.CharField(max_length=80, verbose_name='first name')),
                ('last_name', models.CharField(max_length=80, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(max_length=32, verbose_name='phone')),
                ('check_in', models.DateField(verbose_name='check-in')),
                ('check_out', models.DateField(verbose_name='check-out')),
                ('adults', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='adults')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='children')),
                ('board', models.CharField(choices=[('room_only', 'Room only'), ('bb', 'Bed and breakfast'), ('hb', 'Half board'), ('fb', 'Full board')], default='bb', max_length=20)),
                ('message', models.TextField(blank=True, verbose_name='special request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('language', models.CharField(default='fr', max_length=5, verbose_name='locale of the request')),
            ],
            options={
                'verbose_name': 'reservation request',
                'verbose_name_plural': 'reservation requests',
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='reservation_check_out_after_check_in')],
            },
        ),
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Rate captured at request time, in DZD.', max_digits=10, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='reservations.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_rooms', to='rooms.room')),
            ],
            options={
                'unique_together': {('reservation', 'room')},
            },
        ),
    ]
