# Generated by Django 5.2.16 on 2026-08-03 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('rooms', '0002_room_is_bookable_alter_room_total_units_rateoverride_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='DZD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorised', 'Authorised'), ('captured', 'Captured'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('method', models.CharField(blank=True, choices=[('cib', 'CIB card'), ('edahabia', 'Edahabia'), ('cash', 'Cash'), ('transfer', 'Bank transfer')], max_length=30)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'room assignment',
                'verbose_name_plural': 'room assignments',
                'ordering': ('start_date',),
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='cancellation reason'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('web', 'Website'), ('phone', 'Phone'), ('walk_in', 'Walk-in'), ('ota', 'Online travel agent')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'check_in'], name='reservation_status_90df01_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['check_in', 'check_out'], name='reservation_check_i_87540e_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rooms.roomunit'),
        ),
        migrations.AddIndex(
            model_name='roomassignment',
            index=models.Index(fields=['unit', 'start_date', 'end_date'], name='reservation_unit_id_2755fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomassignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='assignment_end_after_start'),
        ),
    ]
