# Generated by Django 5.2.16 on 2026-07-30 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('surface_m2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='surface (m2)')),
                ('max_adults', models.PositiveSmallIntegerField(default=2, verbose_name='max adults')),
                ('max_children', models.PositiveSmallIntegerField(default=0, verbose_name='max children')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text="In DZD. Leave empty to display 'on request'.", max_digits=10, null=True, verbose_name='nightly rate')),
                ('total_units', models.PositiveSmallIntegerField(default=0, help_text='Used by the availability check.', verbose_name='units in stock')),
                ('video_url', models.URLField(blank=True, verbose_name='video')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ('position', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='alt text')),
                ('is_cover', models.BooleanField(default=False, verbose_name='cover image')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RoomSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic'), ('en', 'English')], db_index=True, max_length=5)),
                ('label', models.CharField(max_length=120, verbose_name='label')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='icon key')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='rooms.room')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RoomTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic'), ('en', 'English')], db_index=True, max_length=5)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='rooms.room')),
            ],
            options={
                'unique_together': {('room', 'language')},
            },
        ),
    ]
