# Generated by Django 5.2.16 on 2026-08-03 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_bookable',
            field=models.BooleanField(db_index=True, default=True, help_text='Stop-sell switch for the console. Distinct from `is_published`, which controls whether the type appears on the public site at all.', verbose_name='open for sale'),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_units',
            field=models.PositiveSmallIntegerField(default=0, help_text='Legacy stock count. Availability now reads RoomUnit rows; keep this in step for display only.', verbose_name='units in stock'),
        ),
        migrations.CreateModel(
            name='RateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='night')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='rate')),
                ('reason', models.CharField(blank=True, max_length=120, verbose_name='reason')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_overrides', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_overrides', to='rooms.room')),
            ],
            options={
                'verbose_name': 'rate override',
                'verbose_name_plural': 'rate overrides',
                'ordering': ('room', 'date'),
                'constraints': [models.UniqueConstraint(fields=('room', 'date'), name='one_override_per_room_per_night')],
            },
        ),
        migrations.CreateModel(
            name='RoomClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='from')),
                ('end_date', models.DateField(help_text='Exclusive, like a check-out date.', verbose_name='until')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='reason')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_closures', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='rooms.room')),
            ],
            options={
                'verbose_name': 'room closure',
                'verbose_name_plural': 'room closures',
                'ordering': ('-start_date',),
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='closure_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='RoomUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=10, verbose_name='room number')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='floor')),
                ('housekeeping', models.CharField(choices=[('clean', 'Clean'), ('occupied', 'Occupied'), ('dirty', 'Dirty'), ('maintenance', 'Out of order')], db_index=True, default='clean', max_length=20, verbose_name='housekeeping')),
                ('is_sellable', models.BooleanField(db_index=True, default=True, help_text='Unset to retire a unit without deleting its booking history.', verbose_name='in inventory')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='rooms.room')),
            ],
            options={
                'verbose_name': 'room unit',
                'verbose_name_plural': 'room units',
                'ordering': ('room', 'number'),
                'constraints': [models.UniqueConstraint(fields=('room', 'number'), name='unique_unit_per_room')],
            },
        ),
    ]
