services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: elmehri
      POSTGRES_USER: elmehri
      POSTGRES_PASSWORD: elmehri
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
