# Generated by Django 5.2.16 on 2026-08-03 00:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_payment_roomassignment_and_more'),
        ('rooms', '0002_room_is_bookable_alter_room_total_units_rateoverride_and_more'),
        ('services', '0002_servicetranslation_kicker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('transport', 'Transport'), ('dining', 'Dining'), ('spa', 'Spa and wellness'), ('housekeeping', 'Housekeeping'), ('technical', 'Technical'), ('other', 'Other')], db_index=True, max_length=20, verbose_name='kind')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal')], db_index=True, default='normal', max_length=20, verbose_name='priority')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('summary', models.CharField(max_length=300, verbose_name='summary')),
                ('detail', models.TextField(blank=True, verbose_name='detail')),
                ('requested_for', models.DateTimeField(blank=True, null=True, verbose_name='requested for')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concierge_requests', to='reservations.reservation')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concierge_requests', to='rooms.roomunit')),
            ],
            options={
                'verbose_name': 'concierge request',
                'verbose_name_plural': 'concierge requests',
                'ordering': ('priority', 'created_at'),
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='concierge_c_status_490412_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExperienceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_name', models.CharField(max_length=150, verbose_name='guest')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='starts at')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='duration (min)')),
                ('party_size', models.PositiveSmallIntegerField(default=1, verbose_name='party size')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='In DZD. Rolls into the reservation total.', max_digits=10, null=True, verbose_name='price')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_bookings', to='reservations.reservation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service')),
            ],
            options={
                'verbose_name': 'experience booking',
                'verbose_name_plural': 'experience bookings',
                'ordering': ('starts_at',),
                'indexes': [models.Index(fields=['status', 'starts_at'], name='concierge_e_status_bcc7d5_idx')],
            },
        ),
    ]
