# Generated by Django 5.2.16 on 2026-07-30 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/')),
                ('cover_alt', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateField(db_index=True, verbose_name='published on')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic'), ('en', 'English')], db_index=True, max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.article')),
            ],
            options={
                'unique_together': {('article', 'language')},
            },
        ),
    ]
