# Generated by Django 5.2.16 on 2026-07-30 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('tea_room', 'Tea lounge'), ('wellness', 'Leisure and wellness'), ('events', 'Events')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('video_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('position', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('seating_capacity', models.PositiveSmallIntegerField(verbose_name='seats')),
                ('surface_m2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='services/halls/')),
                ('service', models.ForeignKey(limit_choices_to={'category': 'events'}, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='services.service')),
            ],
            options={
                'ordering': ('position', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventHallTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic'), ('en', 'English')], db_index=True, max_length=5)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.eventhall')),
            ],
            options={
                'unique_together': {('hall', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ServiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic'), ('en', 'English')], db_index=True, max_length=5)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.service')),
            ],
            options={
                'unique_together': {('service', 'language')},
            },
        ),
    ]
