# Generated by Django 5.2.16 on 2026-08-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetranslation',
            name='kicker',
            field=models.CharField(blank=True, help_text="Short eyebrow label shown above the name, e.g. 'Restaurant central'.", max_length=120, verbose_name='kicker'),
        ),
    ]
