# Generated by Django 5.2.16 on 2026-07-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('content', models.TextField(verbose_name='message')),
                ('language', models.CharField(default='fr', max_length=5)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_handled', models.BooleanField(db_index=True, default=False, verbose_name='handled')),
            ],
            options={
                'verbose_name': 'contact message',
                'verbose_name_plural': 'contact messages',
                'ordering': ('-created_at',),
            },
        ),
    ]
