# Generated by Django 5.2.16 on 2026-08-03 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reservation.create', 'Reservation created'), ('reservation.confirm', 'Reservation confirmed'), ('reservation.cancel', 'Reservation cancelled'), ('reservation.check_in', 'Guest checked in'), ('reservation.check_out', 'Guest checked out'), ('payment.record', 'Payment recorded'), ('rate.override', 'Nightly rate overridden'), ('rate.clear', 'Rate override cleared'), ('room.status', 'Housekeeping status changed'), ('room.closure', 'Room closed for sale'), ('room.bookable', 'Room opened or closed for sale'), ('concierge.status', 'Concierge request advanced'), ('auth.login_failed', 'Failed sign-in')], db_index=True, max_length=60)),
                ('target_type', models.CharField(max_length=60, verbose_name='target model')),
                ('target_id', models.CharField(max_length=60, verbose_name='target id')),
                ('target_label', models.CharField(blank=True, help_text='Human-readable at the time of writing, e.g. the reservation reference.', max_length=200, verbose_name='target label')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Shape: {"field": [before, after]}. Never store secrets or card data.', verbose_name='changes')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for anonymous or system actions; the entry survives the account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit entry',
                'verbose_name_plural': 'audit trail',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx')],
            },
        ),
    ]
