/**
 * Demo fixtures for the admin console.
 *
 * ⚠ Every figure in this file is invented. None of it is the hotel's real
 * occupancy, revenue or guest data, and the console renders a visible "Demo
 * data" badge so nobody mistakes it for a live read. It exists so the interface
 * can be designed, reviewed and tested before the API is built.
 *
 * Replacing it is meant to be a one-file change: each export matches the shape
 * the real endpoint should return (see `types/admin.ts`, where every field the
 * backend cannot yet supply is marked `GAP:`).
 *
 * Guest names are obviously fictional. Real reservation data must never be
 * committed to the repository — it is personal data under Algeria's Law 18-07,
 * and a git history is not a lawful place to keep it.
 */

import type {
  AdminReservation,
  AdminSuite,
  ConciergeRequest,
  ExecutiveMetric,
} from '@/types/admin';

/** Fixed so server and client render identically; `new Date()` here would
    produce a hydration mismatch and a diff on every page load. */
export const DEMO_NOW = new Date('2026-08-03T09:12:00Z');

export const demoMetrics: ExecutiveMetric[] = [
  {
    id: 'occupancy',
    label: 'Occupancy rate',
    value: '78%',
    caption: '37 of 48 units sold tonight',
    deltaPct: 6.2,
    riseIsGood: true,
    tone: 'gold',
    trend: [0.52, 0.58, 0.55, 0.63, 0.69, 0.66, 0.74, 0.78],
  },
  {
    id: 'revenue',
    label: 'Revenue, month to date',
    value: '14.2M DZD',
    caption: 'August, 3 days elapsed',
    deltaPct: 11.4,
    riseIsGood: true,
    tone: 'ok',
    trend: [0.3, 0.36, 0.34, 0.45, 0.52, 0.61, 0.72, 0.83],
  },
  {
    id: 'reservations',
    label: 'Active reservations',
    value: '64',
    caption: '9 awaiting confirmation',
    deltaPct: -3.1,
    riseIsGood: true,
    tone: 'ice',
    trend: [0.71, 0.68, 0.74, 0.7, 0.66, 0.72, 0.69, 0.64],
  },
  {
    id: 'vip',
    label: 'VIP arrivals today',
    value: '3',
    caption: '2 suites, 1 royal suite',
    deltaPct: null,
    riseIsGood: true,
    tone: 'alert',
    trend: [0.2, 0.4, 0.2, 0.6, 0.4, 0.8, 0.6, 0.6],
  },
];

export const demoReservations: AdminReservation[] = [
  {
    reference: 'LYN-4821',
    guestName: 'Amine Belkacem',
    email: 'a.belkacem@example.dz',
    phone: '0770 11 22 33',
    checkIn: '2026-08-03',
    checkOut: '2026-08-07',
    nights: 4,
    adults: 2,
    children: 1,
    board: 'hb',
    status: 'confirmed',
    suite: 'Suite Royale',
    suiteSlug: 'suite-royale',
    totalDzd: 184000,
    paymentStatus: 'deposit_held',
    isVip: true,
    specialRequest: 'Late arrival, around 23:00. Cot for the child.',
    requestedAt: '2026-07-29T14:22:00Z',
  },
  {
    reference: 'LYN-4822',
    guestName: 'Claire Fontaine',
    email: 'c.fontaine@example.fr',
    phone: '+33 6 12 34 56 78',
    checkIn: '2026-08-03',
    checkOut: '2026-08-05',
    nights: 2,
    adults: 1,
    children: 0,
    board: 'bb',
    status: 'checked_in',
    suite: 'Suite Exécutive',
    suiteSlug: 'suite-executive',
    totalDzd: 62000,
    paymentStatus: 'paid',
    isVip: false,
    specialRequest: '',
    requestedAt: '2026-07-30T08:05:00Z',
  },
  {
    reference: 'LYN-4823',
    guestName: 'Yacine Meddour',
    email: 'y.meddour@example.dz',
    phone: '0555 44 88 12',
    checkIn: '2026-08-04',
    checkOut: '2026-08-09',
    nights: 5,
    adults: 2,
    children: 0,
    board: 'fb',
    status: 'pending',
    suite: 'Suite Junior',
    suiteSlug: 'suite-junior',
    totalDzd: 97500,
    paymentStatus: 'unpaid',
    isVip: false,
    specialRequest: 'Quiet room away from the lift if possible.',
    requestedAt: '2026-08-02T19:41:00Z',
  },
  {
    reference: 'LYN-4824',
    guestName: 'Sofia Haddad',
    email: 's.haddad@example.dz',
    phone: '0661 90 34 77',
    checkIn: '2026-08-03',
    checkOut: '2026-08-10',
    nights: 7,
    adults: 2,
    children: 2,
    board: 'hb',
    status: 'confirmed',
    suite: 'Suite Royale',
    suiteSlug: 'suite-royale',
    totalDzd: 322000,
    paymentStatus: 'paid',
    isVip: true,
    specialRequest: 'Anniversary — flowers and patisserie on arrival.',
    requestedAt: '2026-07-21T11:02:00Z',
  },
  {
    reference: 'LYN-4825',
    guestName: 'Karim Ould Ali',
    email: 'k.ouldali@example.dz',
    phone: '0770 55 21 09',
    checkIn: '2026-08-05',
    checkOut: '2026-08-06',
    nights: 1,
    adults: 1,
    children: 0,
    board: 'room_only',
    status: 'pending',
    suite: 'Chambre Standard',
    suiteSlug: 'chambre-standard',
    totalDzd: 14500,
    paymentStatus: 'unpaid',
    isVip: false,
    specialRequest: '',
    requestedAt: '2026-08-03T06:18:00Z',
  },
  {
    reference: 'LYN-4826',
    guestName: 'Nadia Cherif',
    email: 'n.cherif@example.dz',
    phone: '0699 12 45 63',
    checkIn: '2026-08-02',
    checkOut: '2026-08-04',
    nights: 2,
    adults: 2,
    children: 0,
    board: 'bb',
    status: 'checked_in',
    suite: 'Suite Junior',
    suiteSlug: 'suite-junior',
    totalDzd: 39000,
    paymentStatus: 'paid',
    isVip: false,
    specialRequest: '',
    requestedAt: '2026-07-28T16:33:00Z',
  },
  {
    reference: 'LYN-4827',
    guestName: 'Omar Benyoucef',
    email: 'o.benyoucef@example.dz',
    phone: '0550 77 31 24',
    checkIn: '2026-08-06',
    checkOut: '2026-08-08',
    nights: 2,
    adults: 3,
    children: 0,
    board: 'bb',
    status: 'cancelled',
    suite: 'Suite Exécutive',
    suiteSlug: 'suite-executive',
    totalDzd: 62000,
    paymentStatus: 'refunded',
    isVip: false,
    specialRequest: 'Cancelled by guest, 2 August.',
    requestedAt: '2026-07-25T09:47:00Z',
  },
  {
    reference: 'LYN-4828',
    guestName: 'Leïla Zerrouki',
    email: 'l.zerrouki@example.dz',
    phone: '0771 08 55 90',
    checkIn: '2026-08-03',
    checkOut: '2026-08-12',
    nights: 9,
    adults: 2,
    children: 0,
    board: 'fb',
    status: 'confirmed',
    suite: 'Suite Exécutive',
    suiteSlug: 'suite-executive',
    totalDzd: 279000,
    paymentStatus: 'deposit_held',
    isVip: true,
    specialRequest: 'Requests the same suite as her March stay (503).',
    requestedAt: '2026-07-18T13:15:00Z',
  },
];

/** Unit counts mirror `rooms.Room.total_units` in the seed data. */
export const demoSuites: AdminSuite[] = [
  {
    slug: 'suite-royale',
    name: 'Suite Royale',
    tier: 'Royale',
    baseRateDzd: 46000,
    rateOverrideDzd: null,
    isBookable: true,
    units: [
      { id: 'r-601', number: '601', status: 'occupied' },
      { id: 'r-602', number: '602', status: 'clean' },
      { id: 'r-603', number: '603', status: 'dirty' },
      { id: 'r-604', number: '604', status: 'maintenance' },
    ],
  },
  {
    slug: 'suite-executive',
    name: 'Suite Exécutive',
    tier: 'Executive',
    baseRateDzd: 31000,
    rateOverrideDzd: 34500,
    isBookable: true,
    units: [
      { id: 'e-501', number: '501', status: 'occupied' },
      { id: 'e-502', number: '502', status: 'occupied' },
      { id: 'e-503', number: '503', status: 'clean' },
      { id: 'e-504', number: '504', status: 'clean' },
      { id: 'e-505', number: '505', status: 'dirty' },
      { id: 'e-506', number: '506', status: 'clean' },
    ],
  },
  {
    slug: 'suite-junior',
    name: 'Suite Junior',
    tier: 'Junior',
    baseRateDzd: 19500,
    rateOverrideDzd: null,
    isBookable: true,
    units: [
      { id: 'j-401', number: '401', status: 'occupied' },
      { id: 'j-402', number: '402', status: 'clean' },
      { id: 'j-403', number: '403', status: 'occupied' },
      { id: 'j-404', number: '404', status: 'dirty' },
      { id: 'j-405', number: '405', status: 'clean' },
      { id: 'j-406', number: '406', status: 'clean' },
    ],
  },
  {
    slug: 'chambre-standard',
    name: 'Chambre Standard',
    tier: 'Standard',
    baseRateDzd: 14500,
    rateOverrideDzd: null,
    isBookable: false,
    units: [
      { id: 's-301', number: '301', status: 'maintenance' },
      { id: 's-302', number: '302', status: 'maintenance' },
      { id: 's-303', number: '303', status: 'clean' },
      { id: 's-304', number: '304', status: 'occupied' },
      { id: 's-305', number: '305', status: 'clean' },
      { id: 's-306', number: '306', status: 'dirty' },
    ],
  },
];

export const demoRequests: ConciergeRequest[] = [
  {
    id: 'rq-1',
    kind: 'transport',
    priority: 'urgent',
    status: 'new',
    guestName: 'Sofia Haddad',
    isVip: true,
    suite: 'Suite Royale · 602',
    summary: 'Airport transfer to Ouargla for 11:40, two passengers and four cases.',
    receivedAt: '2026-08-03T09:04:00Z',
  },
  {
    id: 'rq-2',
    kind: 'dining',
    priority: 'high',
    status: 'new',
    guestName: 'Leïla Zerrouki',
    isVip: true,
    summary: 'Private table at El Mayda, 20:30, party of four. One guest is coeliac.',
    suite: 'Suite Exécutive · 503',
    receivedAt: '2026-08-03T08:47:00Z',
  },
  {
    id: 'rq-3',
    kind: 'spa',
    priority: 'normal',
    status: 'in_progress',
    guestName: 'Claire Fontaine',
    isVip: false,
    suite: 'Suite Exécutive · 501',
    summary: 'Two massage cabins booked for 17:00. Awaiting therapist confirmation.',
    receivedAt: '2026-08-03T08:12:00Z',
  },
  {
    id: 'rq-4',
    kind: 'housekeeping',
    priority: 'high',
    status: 'new',
    guestName: 'Amine Belkacem',
    isVip: true,
    suite: 'Suite Royale · 601',
    summary: 'Cot requested before 23:00 arrival, plus extra towels.',
    receivedAt: '2026-08-03T07:55:00Z',
  },
  {
    id: 'rq-5',
    kind: 'tech',
    priority: 'normal',
    status: 'in_progress',
    guestName: 'Nadia Cherif',
    isVip: false,
    suite: 'Suite Junior · 403',
    summary: 'Satellite receiver not responding on the bedroom set.',
    receivedAt: '2026-08-03T07:20:00Z',
  },
  {
    id: 'rq-6',
    kind: 'transport',
    priority: 'normal',
    status: 'resolved',
    guestName: 'Yacine Meddour',
    isVip: false,
    suite: 'Suite Junior · 405',
    summary: 'City centre drop-off at 09:00. Completed.',
    receivedAt: '2026-08-03T06:35:00Z',
  },
];
