# Generated by Django 5.2.16 on 2026-07-30 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('tag', models.CharField(choices=[('room', 'Rooms'), ('service', 'Services'), ('event', 'Events'), ('other', 'Other')], default='other', max_length=20)),
            ],
            options={
                'verbose_name': 'media category',
                'verbose_name_plural': 'media categories',
                'ordering': ('position', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('credit', models.CharField(blank=True, max_length=120)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='gallery.mediacategory')),
            ],
            options={
                'verbose_name': 'media asset',
                'verbose_name_plural': 'media assets',
                'ordering': ('position', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic'), ('en', 'English')], db_index=True, max_length=5)),
                ('name', models.CharField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='gallery.mediacategory')),
            ],
            options={
                'unique_together': {('category', 'language')},
            },
        ),
    ]
