# Generated by Django 5.2.16 on 2026-07-30 16:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=120, verbose_name='author')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('language', models.CharField(default='fr', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Awaiting moderation'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, help_text='Empty means a review of the hotel as a whole.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rooms.room')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
